### ISSUE TITLE
Sort by Language Code First, then Name

### ISSUE THREAD

**Issue by jag3773** [Door43/dokuwiki-plugin-translation#2]
Ideally, if I enter 'en' then English (en) should be at the top of the list.  Or, more clearly, if I type 'fr' then "français, langue française (fr)" should be at the top.

**Comment by phillip-hopper** [comment]
@jag3773  You can just type in the language code and hit enter. Does that fulfill this requirement?  And the list is already sorted by language code, so I'm guessing you don't want it literally sorted by language code, but some order that considers language code somehow.

**Comment by jag3773** [comment]
Yes, I think ideally, if 'fr' has been entered, then the "best match" should show first, which would be 'fr', then 'frc', 'frd', etc.  Thus, I don't want an alphabetic sorting of all the results returned, rather it's like flipping to f in the dictionary, you don't see words starting with 'a'.
