### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by jag3773** [Door43/dokuwiki-plugin-translation#3]
It appears that the whole ~868 KB of JSON data is being loaded on every page load.  Ideally, we only want the JSON data to be hit when someone starts typing so that we don't have to load all that data every time.  If we can't do that then we need to make sure that we get that data cached in the browser as it is not currently being cached.

**Comment by phillip-hopper** [comment]
@jag3773 Installed and ready to test on test.door43.org.

**Comment by phillip-hopper** [comment]
Branch Issue-3 merged into master.
